version: "3.8"
services:
  telegram_bot:
    image: "ghcr.io/soerface/l33t_score_bot:${COMMIT_SHA}"
    build:
      context: .
      args:
        COMMIT_SHA: ${COMMIT_SHA}
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
volumes:
  redis-data: