version: "3.8"
services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  redis-data: